src/Entity/Boutique.php
<?php

namespace App\Entity;

use App\Repository\BoutiqueRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BoutiqueRepository::class)]
class Boutique
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255)]
    private ?string $code_postal = null;

    #[ORM\Column(length: 255)]
    private ?string $ville = null;

    #[ORM\Column]
    private ?int $telephone = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\OneToMany(mappedBy: 'boutique', targetEntity: Reservation::class)]
    private Collection $reservations;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): static
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(int $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): static
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations->add($reservation);
            $reservation->setBoutique($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): static
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getBoutique() === $this) {
                $reservation->setBoutique(null);
            }
        }

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;
use App\Entity\ReservationCommande; 
use App\Service\PanierService;
use App\Entity\Materiel;
use App\Entity\Reservation;
use App\Form\ReservationFormType;
use App\Repository\BoutiqueRepository;
use App\Repository\MaterielRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;
use \Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\JsonResponse;

#[Route('/cart', name: 'cart_')]
class CartController extends AbstractController
{
    private $panier;

    public function __construct(PanierService $panier ) {
        $this->panier = $panier;
    }
    const TVA_RATE = 0.10;  // Taux de TVA de 10%. Vous pouvez changer cela selon votre situation.

    #[Route('/reservation', name: 'reservation')]
    public function reservationAndSubmit(
        Request $request, 
        EntityManagerInterface $entityManager,
        SessionInterface $session, 
        MaterielRepository $productsRepository,
        BoutiqueRepository $boutiqueRepository,
        PanierService $panier,
        Security $security
    ): Response {
        $boutiques = $boutiqueRepository->findAll();
        
        $reservation = new Reservation();
        $user = $security->getUser();
        $reservation->setPrenom($user->getPrenom());
        $reservation->setNom($user->getNom());
        $reservation->setEmail($user->getEmail());

        $form = $this->createForm(ReservationFormType::class, $reservation);
        $form->handleRequest($request);
        
        $panier = $session->get("panier", []);
        $total = 0;
        $totalWithTVA = 0;

        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($panier as $itemId => $item) {
                $materielId = $itemId;
                $product = $item['product'];
                $quantity = $item['quantity'];
        
                $total = $item['total'];
                $materiel = $entityManager->getRepository(Materiel::class)->find($materielId);
        
                if ($materiel) {
                    $reservation->addMateriel($materiel);
                }
        
                $tvaAmount = $total * self::TVA_RATE;
                $totalWithTVA = $total + $tvaAmount;
        
                $reservation->setPrixTotal($totalWithTVA);
                $reservation->setUser($user);
        
                $entityManager->persist($reservation);
                $entityManager->flush();
        
                $reservationId = $reservation->getId();
        
                $sql = "UPDATE reservation_materiel SET quantity = :quantity WHERE reservation_id = :reservationId AND materiel_id = :materielId";
                $entityManager->getConnection()->executeQuery($sql, [
                    'quantity' => $quantity,
                    'reservationId' => $reservationId,
                    'materielId' => $materielId,
                ]);
        
                $sql = "UPDATE reservation_materiel SET user_id = :userId WHERE reservation_id = :reservationId AND materiel_id = :materielId";
                $entityManager->getConnection()->executeQuery($sql, [
                    'reservationId' => $reservationId,
                    'materielId' => $materielId,
                    'userId' => $user->getId()
                ]);
            }
        $currentUrl = $request->get('current_url');

            $this->addFlash('success', "Votre demande a bien été envoyée. Nous la traiterons dès que possible.");
        
            $session->remove('panier');
            return $this->redirectToRoute('app_home');
        }
        
    
        return $this->render('cart/index.html.twig', [
            'reservationForm' => $form->createView(),
            'reservation' => $reservation,
            'boutiques' => $boutiques,
            'dataPanier' => $panier,
            'total' => $total,
            'totalWithTVA' => $totalWithTVA,
            'nbItemPanier' => $this->panier->getNbArticles(),
            'totalGeneral' => $this->panier->getTotal(), 
        ]);
    }
    
    

    #[Route("/update-prices", name: "update_prices", methods: ["POST"])]
    public function updatePrices(Request $request, EntityManagerInterface $entityManager): JsonResponse
    {
        $data = json_decode($request->getContent(), true);
        dd($data);
        if (!isset($data['product_quantity'])) {
            return new JsonResponse(['error' => 'Quantities not provided'], 400);
        }

        $totalGeneral = 0;

        foreach ($data['product_quantity'] as $productId => $quantity) {
            $reservation = $entityManager->getRepository(Reservation::class)->find($productId);
            
            if (!$reservation) {
                return new JsonResponse(['error' => 'Product not found'], 400);
            }

            $totalPrice = $reservation->getPrixLocation() * $quantity;
            $totalGeneral += $totalPrice;

            // Assuming the Product entity has a setTotalPrice method
            $reservation->setPrixTotal($totalPrice);
            $entityManager->persist($reservation);
        }

        $entityManager->flush();

        return new JsonResponse(['totalGeneral' => $totalGeneral]);
}

    #[Route('/add/{id}', name: 'add')]
    public function addToCart($id, Materiel $product, SessionInterface $session, Request $request)
    {
        if (!$product) {
            $this->addFlash('error', 'Produit introuvable.');
            return $this->redirectToRoute('route_de_la_page_des_produits');
        }
    
        // Récupérez le prix unitaire du produit depuis la base de données
        $prixUnitaire = $product->getPrixLocation();
    
        $panier = $session->get("panier", []);
        
        if (!isset($panier[$id])) {
            $panier[$id] = [
                'product' => $product,
                'quantity' => 0,
                'total' => 0,
            ];
        }
        
        // Incrémentez la quantité et mettez à jour le total
        $panier[$id]['quantity']++;
        $panier[$id]['total'] = $prixUnitaire * $panier[$id]['quantity'];
        
        $session->set("panier", $panier);

        $currentUrl = $request->get('current_url');

        if ($currentUrl && strpos($currentUrl, 'product_detail') !== false) {
            $this->addFlash('success', "L'article a été ajouté au panier!");
        }

        return $this->redirect($currentUrl);
    }


    #[Route('/remove/{id}', name: 'remove')]
    public function remove(Materiel $product, SessionInterface $session)
    {
        $panier = $session->get("panier", []);
        $id = $product->getId();

        if (isset($panier[$id])) {
            if ($panier[$id]['quantity'] > 1) {
                $panier[$id]['quantity']--;
                $panier[$id]['total'] = $panier[$id]['quantity'] * $panier[$id]['product']->getPrixLocation();
            } else {
                unset($panier[$id]);
            }

            $session->set("panier", $panier);
            return $this->redirectToRoute("cart_reservation");

        }
    }

    
    #[Route('/delete/{id}', name: 'delete')]
    public function delete(Materiel $product, SessionInterface $session)
    {
        $panier = $session->get("panier", []);
        $id = $product->getId();

        if(!empty($panier[$id])){
            unset($panier[$id]);
        }

        $session->set("panier", $panier);
        return $this->redirectToRoute("cart_reservation");
    }

    #[Route('/delete', name: 'delete_all')]
    public function deleteAll(SessionInterface $session)
    {
        $session->remove("panier");
        return $this->redirectToRoute("cart_reservation");
    }

}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-10">
            
            {% for flash_error in app.flashes('verify_email_error') %}
                <div class="alert alert-danger" role="alert">{{ flash_error }}</div>
            {% endfor %}

            <div class="card">
                <div class="card-header bg-dark text-white">
                    <h3 class="mb-0">Réservation</h3>
                </div>
                <div class="card-body">
                    
                    {{ form_start(reservationForm, {'attr': {'class': 'form'}}) }}

                    <h5>ÉTAPE 1 - DATE DE RÉSERVATION</h5>
                    <div class="form-group">
                        {{ form_label(reservationForm.boutique, 'Choix de la boutique *', {'label_attr': {'class': 'form-label'}}) }}
                        {{ form_widget(reservationForm.boutique, {'attr': {'class': 'form-control'}}) }}
                    </div>

                    <div class="form-group">
                        {{ form_label(reservationForm.dateRetrait, 'Date de retrait du matériel *', {'label_attr': {'class': 'form-label'}}) }}
                        {{ form_widget(reservationForm.dateRetrait, {'attr': {'class': 'form-control', 'id': 'date-retrait'}}) }}
                    </div>

                    <div class="form-group">
                        {{ form_label(reservationForm.dateRetour, 'Date de retour du matériel *', {'label_attr': {'class': 'form-label'}}) }}
                        {{ form_widget(reservationForm.dateRetour, {'attr': {'class': 'form-control', 'id': 'date-retour'}}) }}
                    </div>


<h2 class="mt-4">ÉTAPE 2 - BON DE COMMANDE</h2>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>QTY</th>
            <th>ARTICLE</th>
            <th>PRIX UNITAIRE</th>
            <th>TOTAL</th>
            <th>ACTION</th>
        </tr>
    </thead>
    <tbody>
        <!-- Loop through the products in the cart using Twig -->
        {% for item in dataPanier %}
        <tr>
    <td>{{ item.product.id }}</td>


<td>
    <span id="product-quantity-{{ item.product.id }}" data-product-id="{{ item.product.id }}" data-price="{{ item.product.prixLocation }}">
        {{ item.quantity }}
    </span>
</td>



    <td>{{ item.product.nom }}</td>
    <td>{{ item.product.prixLocation }} €</td>
    <td>
        <span id="total-price-{{ item.product.id }}">{{ item.product.prixLocation * item.quantity }}</span> €
    </td>
    <td>
        <a href="{{ path('cart_add', {id: item.product.id, current_url: app.request.uri }) }}" class="btn btn-success"><i class="bi bi-cart-plus"></i></a>
        <a href="{{ path('cart_remove', {id: item.product.id}) }}" class="btn btn-warning"><i class="bi bi-cart-dash"></i></a>
        <a href="{{ path('cart_delete', {id: item.product.id}) }}" class="btn btn-danger"><i class="bi bi-cart-x"></i></a>
    </td>
</tr>
        {% else %}
        <tr>
            <td colspan="5" class="text-center">Votre panier est vide</td>
        </tr>
        {% endfor %}
        <!-- Ajouter une nouvelle ligne pour le total cumulé -->
        <tr>
            <span id="total-general">{{ totalGeneral | number_format(2) }}</span> €
        </tr>
     <tr>
                           <td colspan="4" class="text-right"><strong>Taux de TVA :</strong></td>
                            <td><span id="tva-rate">10%</span></td>
                            <td></td>
                        </tr>

                        <!-- Montant de la TVA -->
                        <tr>
                            <td colspan="4" class="text-right"><strong>Montant de la TVA :</strong></td>
                            <td><span id="tva-amount">{{ (totalGeneral * 0.10) | number_format(2) }}</span> €</td>
                            <td></td>
                        </tr>

                        <!-- Total avec TVA -->
                        <tr>
                            <td colspan="4" class="text-right"><strong>Total avec TVA par jour :</strong></td>
                            <td><span id="total-with-tva">{{ (totalGeneral + (totalGeneral * 0.10)) | number_format(2) }}</span> €</td>
                            <td></td>
                        </tr>                            <!-- Taux de TVA -->
            
    </tbody>
</table>

  {{ form_widget(reservationForm._token) }}
      <div class="mt-4">
      <td>
   
</td>
    </div>
        
    <div class="mb-3">
        {{ form_label(reservationForm.prenom, 'Prénom *') }}
        {{ form_widget(reservationForm.prenom) }}
        {{ form_errors(reservationForm.prenom) }}
    </div>

    <div class="mb-3">
        {{ form_label(reservationForm.nom, 'Nom *') }}
        {{ form_widget(reservationForm.nom) }}
        {{ form_errors(reservationForm.nom) }}
    </div>

    <!-- Champ Société (facultatif) -->
    <div class="mb-3">
        {{ form_label(reservationForm.societe, 'Société (facultatif)') }}
        {{ form_widget(reservationForm.societe) }}
        {{ form_errors(reservationForm.societe) }}
    </div>

    <!-- Champ Numéro TVA (facultatif) -->
    <div class="mb-3">
        {{ form_label(reservationForm.numeroTVA, 'Numéro TVA (facultatif)') }}
        {{ form_widget(reservationForm.numeroTVA) }}
        {{ form_errors(reservationForm.numeroTVA) }}
    </div>

    <!-- Champ Email -->
    <div class="mb-3">
        {{ form_label(reservationForm.email, 'Email *') }}
        {{ form_widget(reservationForm.email) }}
        {{ form_errors(reservationForm.email) }}
    </div>

    <!-- Champ Adresse de facturation -->
    <div class="mb-3">
        {{ form_label(reservationForm.adresse, 'Adresse de facturation *') }}
        {{ form_widget(reservationForm.adresse) }}
        {{ form_errors(reservationForm.adresse) }}
    </div>

    <!-- Champ Ville -->
    <div class="mb-3">
        {{ form_label(reservationForm.ville, 'Ville *') }}
        {{ form_widget(reservationForm.ville) }}
        {{ form_errors(reservationForm.ville) }}
    </div>

    <!-- Champ Code postal -->
    <div class="mb-3">
        {{ form_label(reservationForm.codePostal, 'Code postal *') }}
        {{ form_widget(reservationForm.codePostal) }}
        {{ form_errors(reservationForm.codePostal) }}
    </div>

    <!-- Champ Téléphone -->
    <div class="mb-3">
        {{ form_label(reservationForm.telephone, 'Téléphone *') }}
        {{ form_widget(reservationForm.telephone) }}
        {{ form_errors(reservationForm.telephone) }}
    </div>

    <!-- Champ AccepteConditions -->
    <div class="form-check mb-3">
        {{ form_widget(reservationForm.accepteConditions) }}
        {{ form_label(reservationForm.accepteConditions, 'Je valide les conditions générales d\'utilisation (nouvelle version en date du 03/04/2023)') }}
        {{ form_errors(reservationForm.accepteConditions) }}
    </div>
    <div class="mb-4">
    <button type="submit" class="btn btn-success">Envoyer votre demande de réservation</button>
</div>

  
</div>
{% block javascripts %}
<script>

</script>
{% endblock %}


{% endblock %}